// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from AndroidNDK_GCC_To_Clang.djinni

#include "TestCppImpl.hpp"

namespace example {

        std::shared_ptr<TestCpp> TestCpp::create() {

            return std::make_shared<TestCppImpl>();

        }

    std::string TestCppImpl::getStringTest() {
        return "Test";
    }

}