// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from AndroidNDK_GCC_To_Clang.djinni

#pragma once

#include "TestCpp.hpp"

namespace example {

    class TestCppImpl : public TestCpp {

    public:

        std::string getStringTest();

    private:
    };

}
