// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gcc_to_clang_sqlitecpp.djinni

#include "NativeTestCpp.hpp"  // my header
#include "Marshal.hpp"
#include "NativeTestCpp.hpp"

namespace djinni_generated {

NativeTestCpp::NativeTestCpp() : ::djinni::JniInterface<::example::TestCpp, NativeTestCpp>("com/example/gcc_to_clang_sqlitecpp/TestCpp$CppProxy") {}

NativeTestCpp::~NativeTestCpp() = default;


CJNIEXPORT void JNICALL Java_com_example_gcc_1to_1clang_1sqlitecpp_TestCpp_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::example::TestCpp>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_example_gcc_1to_1clang_1sqlitecpp_TestCpp_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::example::TestCpp::create();
        return ::djinni::release(::djinni_generated::NativeTestCpp::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_example_gcc_1to_1clang_1sqlitecpp_TestCpp_00024CppProxy_native_1getStringTest(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::example::TestCpp>(nativeRef);
        auto r = ref->getStringTest();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
