// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gcc_to_clang_sqlitecpp.djinni

#include "TestCpp.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EXTestCpp;

namespace djinni_generated {

class TestCpp
{
public:
    using CppType = std::shared_ptr<::example::TestCpp>;
    using CppOptType = std::shared_ptr<::example::TestCpp>;
    using ObjcType = EXTestCpp*;

    using Boxed = TestCpp;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

