// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gcc_to_clang_sqlitecpp.djinni

#import <Foundation/Foundation.h>
@class EXTestCpp;


@interface EXTestCpp : NSObject

+ (nullable EXTestCpp *)create;

- (nonnull NSString *)getStringTest;

@end
